from _typeshed import Incomplete
from typing import Any

FLAG_READ: int
FLAG_WRITE: int
FLAG_NOTIFY: int
FLAG_INDICATE: int

class BLE:
    def __init__(self) -> None: ...
    def active(self, active: Any = None) -> Any: ...
    def config(self, *args: Any, **kwargs: Any) -> Any: ...
    def irq(self, handler: Any, trigger: int = 0) -> None: ...
    def gap_scan(self, duration_ms: int = 0, interval_us: int = 128000, window_us: int = 11250, active: bool = False) -> None: ...
    def gap_connect(self, addr_type: int, addr: bytes, scan_interval_us: int = 11250) -> None: ...
    def gap_disconnect(self, conn_handle: int) -> bool: ...
    def gatts_register_services(self, services: Any) -> None: ...
    def gatts_read(self, value_handle: int) -> bytes: ...
    def gatts_write(self, value_handle: int, data: bytes = b'', send_update: bool = False) -> None: ...
    def gatts_notify(self, conn_handle: int, value_handle: int, data: bytes | None = None) -> None: ...
    def gatts_set_buffer(self, value_handle: int, len: int, append: bool = False) -> None: ...
    def gattc_discover_services(self, conn_handle: int, uuid: Any = None) -> None: ...
    def gattc_discover_characteristics(self, conn_handle: int, start_handle: int, end_handle: int, uuid: Any = None) -> None: ...
    def gattc_read(self, conn_handle: int, value_handle: int) -> None: ...
    def gattc_write(self, conn_handle: int, value_handle: int, data: bytes, mode: int = 0) -> None: ...
    def gap_advertise(self, interval_us: int, adv_data: Any = None, resp_data: Any = None, connectable: bool = True) -> None: ...
    def gap_pair(self, conn_handle: int) -> None: ...
    def gap_passkey(self, conn_handle: int, action: int, key: Any) -> None: ...

UUID: Incomplete
