from typing import Any

class DS18X20:
    def __init__(self, onewire: Any) -> None: ...
    def scan(self) -> list[Any]: ...
    def convert_temp(self) -> None: ...
    def read_scratch(self, rom: bytes) -> bytes: ...
    def write_scratch(self, rom: bytes, data: bytes) -> None: ...
    def read_temp(self, rom: bytes) -> float: ...

def __getattr__(name: str) -> Any: ...
