from typing import Any

class OneWire:
    MATCH_ROM: int
    SKIP_ROM: int
    SEARCH_ROM: int
    def __init__(self, pin: Any) -> None: ...
    def reset(self, required: bool = False) -> bool: ...
    def readbit(self) -> int: ...
    def readbyte(self) -> int: ...
    def readinto(self, buf: bytearray) -> None: ...
    def writebit(self, value: int) -> None: ...
    def writebyte(self, value: int) -> None: ...
    def write(self, buf: bytes) -> None: ...
    def select_rom(self, rom: bytes) -> None: ...
    def scan(self) -> list[Any]: ...
    def crc8(self, data: bytes) -> int: ...

class OneWireError(Exception): ...
