from _typeshed import Incomplete
from typing import Any

class LED:
    def __init__(self, id: int) -> None: ...
    def on(self) -> None: ...
    def off(self) -> None: ...
    def toggle(self) -> None: ...
    def intensity(self, value: Any = None) -> Any: ...

class Switch:
    def __init__(self) -> None: ...
    def value(self) -> bool: ...
    def callback(self, func: Any = None) -> Any: ...

class Accel:
    def __init__(self) -> None: ...
    def x(self) -> int: ...
    def y(self) -> int: ...
    def z(self) -> int: ...
    def tilt(self) -> int: ...
    def filtered_xyz(self) -> tuple[Any, ...]: ...

class Servo:
    def __init__(self, id: int) -> None: ...
    def angle(self, value: Any = None) -> Any: ...
    def speed(self, value: Any = None) -> Any: ...
    def pulse_width(self, value: Any = None) -> Any: ...
    def calibration(self, *args: Any) -> Any: ...

delay: Incomplete
udelay: Incomplete
millis: Incomplete
micros: Incomplete
elapsed_millis: Incomplete
elapsed_micros: Incomplete
hard_reset: Incomplete
info: Incomplete
unique_id: Incomplete
freq: Incomplete
repl_uart: Incomplete
usb_mode: Incomplete
have_cdc: Incomplete
hid: Incomplete
main: Incomplete
mount: Incomplete
