import asyncio as _asyncio
from _typeshed import Incomplete
from typing import Any

sleep: Incomplete
sleep_ms: Incomplete
gather: Incomplete
wait_for: Incomplete
wait_for_ms: Incomplete

class Event:
    def __init__(self) -> None: ...
    def is_set(self) -> bool: ...
    def set(self) -> None: ...
    def clear(self) -> None: ...
    async def wait(self) -> None: ...

class Lock:
    def __init__(self) -> None: ...
    def locked(self) -> bool: ...
    async def acquire(self) -> bool: ...
    def release(self) -> None: ...
    async def __aenter__(self) -> Lock: ...
    async def __aexit__(self, *args: Any) -> None: ...

class StreamReader:
    def __init__(self) -> None: ...
    async def read(self, n: int = -1) -> bytes: ...
    async def readline(self) -> bytes: ...
    async def readexactly(self, n: int) -> bytes: ...
    async def wait_closed(self) -> None: ...

class StreamWriter:
    def __init__(self) -> None: ...
    def write(self, buf: bytes) -> None: ...
    async def drain(self) -> None: ...
    def close(self) -> None: ...
    async def wait_closed(self) -> None: ...
    def get_extra_info(self, name: str, default: Any = None) -> Any: ...
    async def __aenter__(self) -> StreamWriter: ...
    async def __aexit__(self, *args: Any) -> None: ...

class Task:
    def __init__(self, coro: Any) -> None: ...
    def cancel(self) -> bool: ...

def create_task(coro: Any) -> Task: ...
def run(coro: Any) -> Any: ...

open_connection: Incomplete
start_server: Incomplete

class ThreadSafeFlag:
    def set(self) -> None: ...
    async def wait(self) -> None: ...

class Semaphore:
    def __init__(self, value: int = 1) -> None: ...
    async def acquire(self) -> bool: ...
    def release(self) -> None: ...

class Queue:
    def __init__(self, maxsize: int = 0) -> None: ...
    async def put(self, item: Any) -> None: ...
    async def get(self) -> Any: ...
    def empty(self) -> bool: ...
    def full(self) -> bool: ...
Loop = _asyncio.AbstractEventLoop
new_event_loop = _asyncio.new_event_loop
get_event_loop: Incomplete
