from _typeshed import Incomplete
from typing import Any

AF_INET: int
AF_INET6: int
AF_UNIX: int
SOCK_STREAM: int
SOCK_DGRAM: int
SOCK_RAW: int
IPPROTO_TCP: int
IPPROTO_UDP: int
IPPROTO_IP: int
SOL_SOCKET: int
SO_REUSEADDR: int
IPPROTO_SEC: int

class socket:
    def __init__(self, af: int = ..., type: int = ..., proto: int = 0, fileno: Any = None) -> None: ...
    def close(self) -> None: ...
    def bind(self, address: Any) -> None: ...
    def listen(self, backlog: int = 1) -> None: ...
    def accept(self) -> tuple[Any, ...]: ...
    def connect(self, address: Any) -> None: ...
    def send(self, bytes: bytes, flags: int = 0) -> int: ...
    def sendall(self, bytes: bytes, flags: int = 0) -> None: ...
    def sendto(self, bytes: bytes, address: Any) -> int: ...
    def recv(self, bufsize: int, flags: int = 0) -> bytes: ...
    def recvfrom(self, bufsize: int, flags: int = 0) -> tuple[Any, ...]: ...
    def recvinto(self, buf: bytearray, nbytes: int = 0, flags: int = 0) -> int: ...
    def setsockopt(self, level: int, optname: int, value: Any) -> None: ...
    def setblocking(self, flag: bool) -> None: ...
    def settimeout(self, value: Any) -> None: ...
    def getaddrinfo(self, host: str, port: int, af: int = 0, type: int = 0, proto: int = 0, flags: int = 0) -> list[Any]: ...
    def makefile(self, mode: str = 'rb', buffering: int = 0, *args: Any) -> Any: ...
    def read(self, size: int = -1) -> bytes: ...
    def readline(self) -> bytes: ...
    def write(self, buf: bytes) -> int: ...
    def __enter__(self) -> socket: ...
    def __exit__(self, *args: Any) -> None: ...

getaddrinfo: Incomplete
gethostbyname: Incomplete
htons: Incomplete
ntohs: Incomplete
inet_aton: Incomplete
inet_ntoa: Incomplete
socket = socket
