from typing import Any

class DHT11:
    def __init__(self, pin: Any) -> None: ...
    def measure(self) -> None: ...
    def temperature(self) -> float: ...
    def humidity(self) -> float: ...

class DHT22(DHT11): ...
