from _typeshed import Incomplete
from typing import Any

wake_on_touch: Incomplete
wake_on_ext0: Incomplete
wake_on_ext1: Incomplete
gpio_deep_sleep_hold: Incomplete

class ULP:
    def __init__(self) -> None: ...
    def set_wakeup_period(self, period_index: int, period_us: int) -> None: ...
    def load_binary(self, load_addr: int, program: bytes) -> None: ...
    def run(self, entry_point: int) -> None: ...

class NVS:
    def __init__(self, name: str) -> None: ...
    def get_i32(self, key: str) -> int: ...
    def set_i32(self, key: str, value: int) -> None: ...
    def commit(self) -> None: ...
    def erase_key(self, key: str) -> None: ...

class Partition:
    RUNNING: int
    BOOT: int
    TYPE_APP: int
    TYPE_DATA: int
    def __init__(self, id: Any, block_size: int = 0, offset: int = 0) -> None: ...
    @classmethod
    def find(cls, type: int = 0, subtype: int = 0, label: str | None = None) -> list[Any]: ...
    def info(self) -> tuple[Any, ...]: ...
    def readblocks(self, block_num: int, buf: bytearray) -> int: ...
    def writeblocks(self, block_num: int, buf: bytes) -> int: ...
    def ioctl(self, op: int, arg: Any) -> int: ...
    def set_boot(self) -> None: ...
    def get_next_update(self) -> Partition: ...

class RMT:
    def __init__(self, channel: int, *, pin: Any = None, clock_div: int = 8, carrier_freq: int = 0, carrier_duty_percent: int = 50) -> None: ...
    def source_freq(self) -> int: ...
    def clock_div(self) -> int: ...
    def wait_done(self, timeout: int = 0) -> None: ...
    def loop(self, enable_loop: bool) -> None: ...
    def write_pulses(self, duration: Any, start: int = 1) -> None: ...

IDF: Incomplete
raw_temperature: Incomplete
hall_sensor: Incomplete

def __getattr__(name: str) -> Any: ...
