from _typeshed import Incomplete
from typing import Any

MONO_VLSB: int
MONO_HLSB: int
MONO_HMSB: int
RGB565: int
GS2_HMSB: int
GS4_HMSB: int
GS8: int

class FrameBuffer:
    width: Incomplete
    height: Incomplete
    def __init__(self, buffer: Any, width: int, height: int, format: int, stride: int = 0) -> None: ...
    def fill(self, c: int) -> None: ...
    def pixel(self, x: int, y: int, c: int | None = None) -> Any: ...
    def hline(self, x: int, y: int, w: int, c: int) -> None: ...
    def vline(self, x: int, y: int, h: int, c: int) -> None: ...
    def line(self, x1: int, y1: int, x2: int, y2: int, c: int) -> None: ...
    def rect(self, x: int, y: int, w: int, h: int, c: int) -> None: ...
    def fill_rect(self, x: int, y: int, w: int, h: int, c: int) -> None: ...
    def text(self, s: str, x: int, y: int, c: int = 1) -> None: ...
    def scroll(self, xstep: int, ystep: int) -> None: ...
    def blit(self, fbuf: Any, x: int, y: int, key: int = -1, palette: Any = None) -> None: ...
    def draw_rect(self, x: int, y: int, w: int, h: int, c: int) -> None: ...

Font: Incomplete
