from _typeshed import Incomplete
from typing import Any

PWRON_RESET: int
HARD_RESET: int
WDT_RESET: int
SOFT_RESET: int
DEEPSLEEP_RESET: int
IDLE: int
SLEEP: int
DEEPSLEEP: int
Pin_IN: int
Pin_OUT: int
Pin_OPEN_DRAIN: int
Pin_PULL_UP: int
Pin_PULL_DOWN: int
Pin_DRIVE_0: int
Pin_DRIVE_1: int
Pin_DRIVE_2: int
Pin_DRIVE_3: int
Pin_IRQ_FALLING: int
Pin_IRQ_RISING: int
Pin_IRQ_LOW_LEVEL: int
Pin_IRQ_HIGH_LEVEL: int
reset: Incomplete
soft_reset: Incomplete
unique_id: Incomplete
freq: Incomplete
idle: Incomplete
sleep: Incomplete
deepsleep: Incomplete
disable_irq: Incomplete
enable_irq: Incomplete
time_pulse_us: Incomplete
dht_readinto: Incomplete

class Pin:
    IN = Pin_IN
    OUT = Pin_OUT
    OPEN_DRAIN = Pin_OPEN_DRAIN
    PULL_UP = Pin_PULL_UP
    PULL_DOWN = Pin_PULL_DOWN
    DRIVE_0 = Pin_DRIVE_0
    DRIVE_1 = Pin_DRIVE_1
    DRIVE_2 = Pin_DRIVE_2
    DRIVE_3 = Pin_DRIVE_3
    IRQ_FALLING = Pin_IRQ_FALLING
    IRQ_RISING = Pin_IRQ_RISING
    IRQ_LOW_LEVEL = Pin_IRQ_LOW_LEVEL
    IRQ_HIGH_LEVEL = Pin_IRQ_HIGH_LEVEL
    def __init__(self, id: Any, mode: int = -1, pull: int = -1, *, value: Any = None, drive: int = 0, alt: int = -1) -> None: ...
    def value(self, x: Any = None) -> Any: ...
    def on(self) -> None: ...
    def off(self) -> None: ...
    def toggle(self) -> None: ...
    def irq(self, handler: Any = None, trigger: int = 0, *, hard: bool = False) -> Any: ...
    def mode(self, mode: Any = None) -> Any: ...
    def pull(self, pull: Any = None) -> Any: ...
    def drive(self, drive: Any = None) -> Any: ...
    def init(self, mode: int = -1, pull: int = -1, *, value: Any = None, drive: int = 0, alt: int = -1) -> None: ...
    def deinit(self) -> None: ...
    def __call__(self, x: Any = None) -> Any: ...

class Signal:
    def __init__(self, pin_obj: Any, invert: bool = False, *, pin: Any = None) -> None: ...
    def value(self, x: Any = None) -> Any: ...
    def on(self) -> None: ...
    def off(self) -> None: ...

class ADC:
    WIDTH_9BIT: int
    WIDTH_10BIT: int
    WIDTH_11BIT: int
    WIDTH_12BIT: int
    ATTN_0DB: int
    ATTN_2_5DB: int
    ATTN_6DB: int
    ATTN_11DB: int
    def __init__(self, pin: Any, *, atten: int = ..., width: int = ...) -> None: ...
    def read(self) -> int: ...
    def read_u16(self) -> int: ...
    def read_uv(self) -> int: ...
    def atten(self, attenuation: Any = None) -> Any: ...
    def width(self, width: Any = None) -> Any: ...
    def block(self) -> Any: ...

class PWM:
    def __init__(self, dest: Any, *, freq: int = 1000, duty: int = 0, duty_u16: int = 0, duty_ns: int = 0) -> None: ...
    def deinit(self) -> None: ...
    def freq(self, value: Any = None) -> Any: ...
    def duty(self, value: Any = None) -> Any: ...
    def duty_u16(self, value: Any = None) -> Any: ...
    def duty_ns(self, value: Any = None) -> Any: ...

class I2C:
    def __init__(self, id: Any, *, scl: Any = None, sda: Any = None, freq: int = 400000, timeout: int = 0) -> None: ...
    def scan(self) -> list[Any]: ...
    def readfrom(self, addr: int, nbytes: int, stop: bool = True) -> bytes: ...
    def readfrom_into(self, addr: int, buf: bytearray, stop: bool = True) -> None: ...
    def writeto(self, addr: int, buf: bytes, stop: bool = True) -> int: ...
    def writevto(self, addr: int, vector: Any, stop: bool = True) -> int: ...
    def readfrom_mem(self, addr: int, memaddr: int, nbytes: int, *, addrsize: int = 8) -> bytes: ...
    def readfrom_mem_into(self, addr: int, memaddr: int, buf: bytearray, *, addrsize: int = 8) -> None: ...
    def writeto_mem(self, addr: int, memaddr: int, buf: bytes, *, addrsize: int = 8) -> None: ...

class SoftI2C(I2C): ...

class SPI:
    MSB: int
    LSB: int
    def __init__(self, id: Any, *, baudrate: int = 500000, polarity: int = 0, phase: int = 0, bits: int = 8, sck: Any = None, mosi: Any = None, miso: Any = None, firstbit: int = ..., cs: Any = None) -> None: ...
    def deinit(self) -> None: ...
    def init(self, *, baudrate: int = 500000, polarity: int = 0, phase: int = 0, bits: int = 8, firstbit: int = ...) -> None: ...
    def read(self, nbytes: int, write: int = 0) -> bytes: ...
    def readinto(self, buf: bytearray, write: int = 0) -> None: ...
    def write(self, buf: bytes) -> None: ...
    def write_readinto(self, write_buf: bytes, read_buf: bytearray) -> None: ...

class SoftSPI(SPI): ...

class UART:
    def __init__(self, id: Any, baudrate: int = 115200, bits: int = 8, parity: Any = None, stop: int = 1, *, tx: Any = None, rx: Any = None, rts: Any = None, cts: Any = None, txbuf: Any = None, rxbuf: Any = None, timeout: int = 0, timeout_char: int = 0, invert: Any = None, flow: Any = None) -> None: ...
    def deinit(self) -> None: ...
    def any(self) -> int: ...
    def read(self, nbytes: Any = None) -> bytes: ...
    def readinto(self, buf: bytearray, nbytes: Any = None) -> Any: ...
    def readline(self) -> bytes: ...
    def write(self, buf: bytes) -> int: ...
    def sendbreak(self) -> None: ...
    def irq(self, handler: Any = None, trigger: Any = 0, hard: bool = False) -> Any: ...

class Timer:
    ONE_SHOT: int
    PERIODIC: int
    def __init__(self, id: Any = -1, *, mode: int = ..., callback: Any = None, freq: Any = None, period: Any = None) -> None: ...
    def init(self, *, mode: int = ..., callback: Any = None, freq: Any = None, period: Any = None) -> None: ...
    def deinit(self) -> None: ...

class RTC:
    def __init__(self, id: Any = 0) -> None: ...
    def datetime(self, datetimetuple: Any = None) -> Any: ...

class WDT:
    def __init__(self, id: int = 0, timeout: int = 5000) -> None: ...
    def feed(self) -> None: ...

class TouchPad:
    def __init__(self, pin: Any) -> None: ...
    def read(self) -> int: ...
    def config(self, value: Any = None) -> Any: ...

def __getattr__(name: str) -> Any: ...
