from _typeshed import Incomplete
from typing import Any

class NeoPixel:
    n: Incomplete
    def __init__(self, pin: Any, n: int, *, bpp: int = 3, timing: int = 1) -> None: ...
    def __setitem__(self, index: int, val: Any) -> None: ...
    def __getitem__(self, index: int) -> Any: ...
    def __len__(self) -> int: ...
    def write(self) -> None: ...
    def fill(self, color: Any) -> None: ...
