from typing import Any

STA_IF: int
AP_IF: int
AUTH_OPEN: int
AUTH_WEP: int
AUTH_WPA_PSK: int
AUTH_WPA2_PSK: int
AUTH_WPA_WPA2_PSK: int
AUTH_WPA3_PSK: int
AUTH_WPA2_WPA3_PSK: int
PHY_LAN8720: int
PHY_TLK110: int
PHY_IP101: int
PHY_RTL8201: int
PHY_DP83848: int

class WLAN:
    def __init__(self, interface_id: int = ...) -> None: ...
    def active(self, is_active: Any = None) -> Any: ...
    def connect(self, ssid: Any = None, key: Any = None, *args: Any, **kwargs: Any) -> None: ...
    def disconnect(self) -> None: ...
    def scan(self) -> list[Any]: ...
    def isconnected(self) -> bool: ...
    def ifconfig(self, config: Any = None) -> Any: ...
    def config(self, *args: Any, **kwargs: Any) -> Any: ...
    def status(self, param: Any = None) -> Any: ...
    def mac(self) -> bytes: ...

class LAN:
    def __init__(self, id: Any = 0, *, phy_type: Any = None, phy_addr: int = 0, mdc: Any = None, mdio: Any = None) -> None: ...
    def active(self, is_active: Any = None) -> Any: ...
    def isconnected(self) -> bool: ...
    def ifconfig(self, config: Any = None) -> Any: ...
    def config(self, *args: Any, **kwargs: Any) -> Any: ...

class AbstractNIC:
    def active(self, is_active: Any = None) -> Any: ...
    def isconnected(self) -> bool: ...
    def ifconfig(self, config: Any = None) -> Any: ...

class Bluetooth:
    def __init__(self, id: int = 0) -> None: ...
    def active(self, is_active: Any = None) -> Any: ...
    def config(self, *args: Any, **kwargs: Any) -> Any: ...
