from _typeshed import Incomplete
from typing import Any

PIO0: int
PIO1: int

class PIO:
    def __init__(self, id: int) -> None: ...
    def add_program(self, prog: Any) -> None: ...
    def remove_program(self, prog: Any = None) -> None: ...
    def state_machine(self, id: int, program: Any, *, freq: int = -1, in_base: Any = None, out_base: Any = None, set_base: Any = None, sideset_base: Any = None, jmp_pin: Any = None, push_thresh: int = 32, pull_thresh: int = 32) -> StateMachine: ...

class StateMachine:
    def __init__(self, id: Any, program: Any, *, freq: int = -1, in_base: Any = None, out_base: Any = None, set_base: Any = None, sideset_base: Any = None, jmp_pin: Any = None, push_thresh: int = 32, pull_thresh: int = 32) -> None: ...
    def active(self, value: Any = None) -> Any: ...
    def restart(self) -> None: ...
    def exec(self, instr: Any) -> None: ...
    def get(self, buf: Any = None, shift: int = 0) -> Any: ...
    def put(self, value: Any, shift: int = 0) -> None: ...
    def rx_fifo(self) -> int: ...
    def tx_fifo(self) -> int: ...
    def irq(self, handler: Any) -> Any: ...

def asm_pio(**kwargs: Any) -> Any: ...

PIOIN: int
PIOOUT: int
PIOIRQ: int
bootsel_button: Incomplete
country: Incomplete

def __getattr__(name: str) -> Any: ...
