from typing import Any

class _MockHash:
    def __init__(self, data: bytes = b'') -> None: ...
    def update(self, data: bytes) -> None: ...
    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...

class md5(_MockHash): ...
class sha1(_MockHash): ...
class sha256(_MockHash): ...
class sha512(_MockHash): ...

def new(name: str, data: bytes = b'') -> Any: ...
