from _typeshed import Incomplete
from typing import Any

class poll:
    def __init__(self) -> None: ...
    def register(self, obj: Any, eventmask: int = 1) -> None: ...
    def unregister(self, obj: Any) -> None: ...
    def modify(self, obj: Any, eventmask: int = 1) -> None: ...
    def poll(self, timeout: int = -1) -> list[Any]: ...
    def ipoll(self, timeout: int = -1, flags: int = 0) -> Any: ...

select: Incomplete
POLLIN: int
POLLOUT: int
POLLERR: int
POLLHUP: int
